# Translation Corrector

## About
This notebook validates the the German and English translations.

There are two phases:

- the first phase just checks the structural aspects of the AsciiDoc files. It makes life so easier if there are the same amount of text lines and blank lines for each language section. The result are hint where the structure of one translation doesn't match the other.
- the second phase checks for content and differences between the translations. The result is a assessment sheet as well as merge files that include corrections. Note that this makes only sense to use if the files are structural identical because the translation checks on a line-by-line basis.

## Prerequisites



### Load all relevant files

In [1]:
import glob

# get all AsciiDoc files (hack: starting with "0", doesn't support more chapters > 9)
all_adoc_files = glob.glob('../docs/0*/*.adoc', recursive=True)

# filter out
# - "00-introduction" because they are just the files for combining AsciiDoc files
# - the reference list with books where translation validation makes no sense
file_list = [f for f in all_adoc_files if not f.endswith('00-introduction.adoc') and not f.endswith('00-references.adoc')]

print(f"{len(file_list)} files found.")
file_list[:5] # just show first 5 items to not clutter the notebook with too much text

55 files found.

['../docs\\00-preamble\\01-what-to-expect.adoc',
 '../docs\\00-preamble\\02-out-of-scope.adoc',
 '../docs\\00-preamble\\03-prerequisites.adoc',
 '../docs\\00-preamble\\04-structure-timing-didactics.adoc',
 '../docs\\00-preamble\\05-exam-relevance-levels.adoc']

### Helper function: show output as HTML

This function used at the end of a cell will render the later included links accordingly

In [48]:
from notebook import notebookapp
from IPython.display import display, HTML

def show(df):
    return display(HTML(df.to_html(escape=False)))

### Import files into a pandas DataFrames

In [103]:
import pandas as pd



import os

df_list = []

# make a Dataframe for each file
for file in file_list:

    # read in the AsciiDoc file, keep the blank lines for the line numbers
    df = pd.read_csv(file, names=['text'], sep="\r", skip_blank_lines=False)

     # add file name as first column
    df.insert(0,'filename',file)

    # Mark the rows with language tags
    df.loc[df['text'] == '// tag::DE[]', 'lang'] = 'DE'
    df.loc[df['text'] == '// tag::EN[]', 'lang'] = 'EN'

    # Forward fill the 'lang' column to propagate the tags to the subsequent rows
    df['lang'] = df['lang'].ffill()

    # add line numbers in file
    df['line'] = df.index + 1

    df_de = df[df['lang'] == 'DE'].reset_index(drop=True)
    df_en = df[df['lang'] == 'EN'].reset_index(drop=True)
    
    # Create Side-by-Side (sbs) Dataframe
    sbs_df = df_de[['filename', 'text', 'line']].join(df_en[['text', 'line']], lsuffix="_DE", rsuffix="_EN")

    # Enrich Dataframe with direct links into file in VS Code via HTML
    # Maybe the `replace` at the end needs to be adjusted to whatever IDE and operating system you have, but the default should work fine for most environments
    urls_DE = sbs_df.apply(lambda x: f"<a href=\"vscode://file/{os.path.abspath(x['filename'])}:{float(x['line_DE'])}\">{float(x['line_DE'])}</a>".replace("/mnt/c/", "C:/"), axis=1).apply(lambda x: f"{x}")
    urls_EN = sbs_df.apply(lambda x: f"<a href=\"vscode://file/{os.path.abspath(x['filename'])}:{float(x['line_EN'])}\">{float(x['line_EN'])}</a>".replace("/mnt/c/", "C:/"), axis=1).apply(lambda x: f"{x}")
    sbs_df.insert(sbs_df.columns.get_loc('line_DE') + 1, 'link_DE', urls_DE)
    sbs_df.insert(sbs_df.columns.get_loc('line_EN') + 1, 'link_EN', urls_EN)

    df_list.append(sbs_df)

structural_df = pd.concat(df_list, ignore_index=True)
show(structural_df.head())

## Outputs

### Learning Goals

In [138]:
learning_goals = structural_df[structural_df['text_DE'].fillna('').str.startswith("==== LZ")]['text_DE']
learning_goals = learning_goals.str.replace("==== ", "").replace("\ \[.*\]", "", regex=True)
learning_goals.head()

207    LZ 01-01: Definitionen von Softwarearchitektur...
220    LZ 01-02: Ziele und Nutzen von Softwarearchite...
235    LZ 01-03: Aufgaben und Verantwortung von Softw...
257    LZ 01-04: Abgrenzung zu anderen Architekturdom...
277    LZ 01-05: Rolle von Softwarearchitekt:innen mi...
Name: text_DE, dtype: object

### R1 Learning Goals

In [139]:
learning_goals_r1 = learning_goals[learning_goals.str.contains("R1")]
learning_goals_r1

207    LZ 01-01: Definitionen von Softwarearchitektur...
220    LZ 01-02: Ziele und Nutzen von Softwarearchite...
235    LZ 01-03: Aufgaben und Verantwortung von Softw...
277    LZ 01-05: Rolle von Softwarearchitekt:innen mi...
334     LZ 02-01: Stakeholder-Anliegen verstehen (R1-R3)
374    LZ 02-02: Anforderungen und Randbedingungen kl...
418    LZ 02-03: Qualitäten eines Softwaresystems ver...
448    LZ 02-04: Anforderungen an Qualitäten formulie...
461    LZ 02-05: Explizite Aussagen vor impliziten An...
514    LZ 03-01: Anforderungen durch Architektur erre...
527       LZ 03-02: Softwarearchitekturen entwerfen (R1)
545    LZ 03-03: Vorgehen und Heuristiken zur Archite...
561    LZ 03-04: Entwurfsprinzipien erläutern und anw...
616    LZ 03-05: Zusammenhang zwischen Feedback-Schle...
632    LZ 03-06: Abhängigkeiten von Bausteinen manage...
659    LZ 03-07: Schnittstellen entwerfen und festleg...
681    LZ 03-08: Wichtige Architekturmuster beschreib...
740    LZ 03-10: Querschnittsthemen identifizieren un...
813    LZ 04-01: Anforderungen an technische Dokument...
826    LZ 04-02: Softwarearchitekturen beschreiben un...
880    LZ 04-05: Architektursichten erläutern und anw...
896          LZ 04-06: Schnittstellen dokumentieren (R1)
918    LZ 04-08: Architekturentscheidungen erläutern ...
970    LZ 05-01: Gründe für Architekturanalyse kennen...
983    LZ 05-02: Qualitäten eines Softwaresystems ana...
Name: text_DE, dtype: object

## Cleaning Phase I: Structural checking

### Check for different blank lines

Check which lines in the German version are blank but not so in the English version.

You can delete the `head()` method in the line before the last line for showing all findings.

Tip: Work backwards from the bottom to the top when you want to fix this manally.

Pro-Tip: Introduce a automated formatting for AsciiDoc file or write a tool (if existent)

In [104]:
# Filter rows where both text_DE and text_EN are not NaN at the same time
blanks_df = structural_df[(structural_df['text_DE'].isna() & ~structural_df['text_EN'].isna())]

print(f"{len(blanks_df)} differences regarding lines found!")
# Display the filtered DataFrame
# hint: remove the `.head()` method to get a complete list
display(HTML(blanks_df.head().to_html(escape=False)))

116 differences regarding lines found!

### Check for wrong abbreviations

In [105]:
ev_de_check = structural_df[structural_df['text_DE'].fillna('').str.contains("e\.V\.")]
display(HTML(ev_de_check.to_html(escape=False)))

In [106]:
ev_en_check = structural_df[structural_df['text_EN'].fillna('').str.contains("e\.V\.")]
display(HTML(ev_en_check.to_html(escape=False)))

### Check for different amount of sentences in a line

In [107]:
import nltk
from nltk.tokenize import sent_tokenize

nltk.download('punkt', quiet=True)

sentence_de_count = lambda x : len(sent_tokenize(x, "german"))
sentence_en_count = lambda x : len(sent_tokenize(x, "english"))


structural_df['sentence_count_DE'] = structural_df['text_DE'].fillna('').apply(sentence_de_count)
structural_df['sentence_count_EN'] = structural_df['text_EN'].fillna('').apply(sentence_en_count)

different_amount_of_sentences_df = structural_df[structural_df['sentence_count_DE'] != structural_df['sentence_count_EN']]

print(f"{len(different_amount_of_sentences_df)} differences regarding amount of sentences found!")

# just display the first finding per file because the other findings might be subsequent errors
sentences_df_grouped = different_amount_of_sentences_df.groupby("filename").first()

print("\nFirst errors per file:")
display(HTML(sentences_df_grouped.to_html(escape=False)))

283 differences regarding amount of sentences found!

First errors per file:

## Phase II: Translation correction

### Prepare Dataframe

Am additional Dataframe based on the `structural_df`.  For this, we simplay drop all blank lines which don't need to be checked.

In [102]:
result_dfs = []

for filename, group in structural_df.groupby('filename'):
    # Reset index for each group to ensure correct row ordering
    group = group.reset_index(drop=True)

    # Remove NaN rows for DE section and shift the rest upwards
    non_nan_de = group.dropna(subset=['text_DE']).reset_index(drop=True)
    group['text_DE'], group['line_DE'] = non_nan_de['text_DE'], non_nan_de['line_DE']
    
    # Remove NaN rows for EN section and shift the rest upwards
    non_nan_en = group.dropna(subset=['text_EN']).reset_index(drop=True)
    group['text_EN'], group['line_EN'] = non_nan_en['text_EN'], non_nan_en['line_EN']
    
    # Append the processed group back to the result list
    result_dfs.append(group)

# Concatenate all the processed groups back together
translations_df = pd.concat(result_dfs, ignore_index=True).dropna(subset=['text_DE', 'line_DE', 'text_EN', 'line_EN'], how='all')

display(HTML(translations_df.to_html(escape=False)))

In [65]:
base_df_de = base_df[base_df['lang'] == 'DE'].reset_index(drop=True)
base_df_en = base_df[base_df['lang'] == 'EN'].reset_index(drop=True)

# just keep what's not the same
structural_df = base_df_de[['filename', 'text', 'line']].join(base_df_en[['text', 'line']], lsuffix="_DE", rsuffix="_EN")
structural_df.head(10)

In [27]:
translations = structural_df.dropna(subset=['text_DE', 'text_EN'], how="all")
translations.head(10)

,filename,text_DE,line_DE,text_EN,line_EN
0,../docs\00-preamble\01-what-to-expect.adoc,// tag::DE[],1,// tag::EN[],36
1,../docs\00-preamble\01-what-to-expect.adoc,=== Was dieser Lehrplan enthält,2,=== What Does this Curriculum Contain,37
2,../docs\00-preamble\01-what-to-expect.adoc,Dieser Lehrplan für den _Certified Professiona...,3,This curriculum for the Certified Professional...,38
4,../docs\00-preamble\01-what-to-expect.adoc,Seine Struktur orientiert sich an den grundleg...,5,It is structured along the fundamental activit...,40
6,../docs\00-preamble\01-what-to-expect.adoc,* Anforderungen und Randbedingungen klären,7,* Clarifying stakeholder requirements and cons...,42
7,../docs\00-preamble\01-what-to-expect.adoc,* Entwurf und Entwicklung von Softwarearchitek...,8,* Designing and developing software architectu...,43
8,../docs\00-preamble\01-what-to-expect.adoc,* Beschreiben und Kommunizieren von Softwarear...,9,* Communicating and documenting the architectu...,44
9,../docs\00-preamble\01-what-to-expect.adoc,* Analysieren und Bewerten von Softwarearchite...,10,* Analyzing and assessing software architectures,45
12,../docs\00-preamble\01-what-to-expect.adoc,NaN,13,=== What Does a Foundation Level Training Convey?,48
13,../docs\00-preamble\01-what-to-expect.adoc,=== Was vermittelt eine Foundation-Level-Schul...,14,Licensed Certified Professional for Software A...,49

### Set up OpenAI
This cell configures OpenAI's ChatGPT. The very important part is the structured response format of the request to ChatGPT.

There is also a separate file written just in case of failures of the calls to OpenAI. Technically, you could read in this file and work with it afterwards.

In [7]:
from openai import OpenAI
import os

# set the role of the LLM
ai_system = """
You are a translator for iSAQB curricula between German and English.
Your task is to identify translation errors and inconsistencies between translations."
"""

# define the schema and format including what we expect from the LLM's result
response_json_format = {
    "type": "json_schema",
    "json_schema": {
        "name": "result",
        "schema": {
            "type": "object",
            "properties": {
                "correctness": {
                    "type": "number",
                    "description" : "a value between 0 and 1 that indicates how well the two texts fit together"},
                "assessment": {
                    "type": "string",
                    "description" : "a brief assessment of how good the translation into English is"},
                "corrected_text_de": {
                    "type": "string",
                    "description" : "an improved translation of the German text"},
                "corrected_text_en": {
                        "type": "string",
                        "description": "an improved translation of the English text"}
            },
            "required": ["correctness", "assessment", "corrected_text_de", "corrected_text_en"],
            "additionalProperties": False
        },
        "strict": True
    }
}

openai_client = OpenAI(
   api_key = os.environ["OPENAI_API_KEY"]
)

# the magic function that does all the work for us!
def correct_translation(content):

    messages=[
        {"role": "system", "content": ai_system},
        {"role": "user", "content": content}
    ]

    completion = openai_client.chat.completions.create(
        model="gpt-4o-mini",
        messages = messages,
        response_format = response_json_format,
        temperature = 0,
        n=1)

    return completion.choices[0]

### Create corrected translations

This is the core of this notebook. It sends the German and the English translation to ChatGPT and requests an assessment.

Note: This might take very long for huge data. With `translations_to_correct`, you can just set a subset of the data to correct.m

In [15]:
import json


# this enables just to check a subset of the files
translations_to_correct = translations[:10].reset_index(drop=True)


cache_filepath = "llm_results.json"
# Clear the file by opening it in write mode initially
with open(cache_filepath, 'w') as json_file:
    pass  # This clears the file

results = []

# Open the JSON file in append mode
with open(cache_filepath, 'a') as json_file:
    for i, r in translations_to_correct.iterrows():
        try:
            # Define the prompt for the LLM
            prompt = f"""
            Here is the German and English translation: 

            German text:

            {r['text_DE']}

            English text:

            {r['text_EN']}

            Keep the AsciiDoc formatting as it is. Give also hints and corrections if there are differences between the German formatting and the English formatting.

            Return a result in the defined JSON schema.
            """

            # Call the translation correction function
            result = correct_translation(prompt)

            # Convert the result to a Python dictionary
            result_dict = json.loads(result.message.content)

            # Append the result to the result list
            results.append(result_dict)

            # Append the result to the JSON file
            json.dump(result_dict, json_file)
            json_file.write('\n')  # Add a new line for each result

            # Optional: Immediately flush the file to ensure the result is written
            json_file.flush()

        except Exception as e:
            # Log the error and continue with the next row
            print(f"Error occurred on row {i}: {str(e)}")

result_df = pd.DataFrame.from_dict(results)
result_df.head(5)

,correctness,assessment,corrected_text_de,corrected_text_en
0,0.0,"The provided texts are empty, making it imposs...",,
1,0.9,"The translation is mostly accurate, but the En...",=== Was dieser Lehrplan enthält,=== What this Curriculum Contains
2,0.9,"The translation is mostly accurate, but there ...",Dieser Lehrplan für den _Certified Professiona...,This curriculum for the _Certified Professiona...
3,0.9,"The translation is mostly accurate, but the ph...",Seine Struktur orientiert sich an den grundleg...,Its structure is oriented towards the fundamen...
4,0.7,The translation captures the general meaning b...,* Anforderungen und Randbedingungen klären,* Clarifying requirements and constraints

### Combine assessment result with content datam

In [16]:
assessed_content = translations_to_correct.join(result_df)[[
    'filename',
    'link',
    'text_DE',
    'corrected_text_de',
    'text_EN',
    'corrected_text_en',
    'correctness',
    'assessment',
    'line_DE',
    'line_EN']]

assessed_content.head(1)

,filename,link,text_DE,corrected_text_de,text_EN,corrected_text_en,correctness,assessment,line_DE,line_EN
0,../docs\00-preamble\01-what-to-expect.adoc,"<a href=""vscode://file/c:\dev\repos\curriculum...",// tag::DE[],,// tag::EN[],,0.0,"The provided texts are empty, making it imposs...",1,36

### Correct metadata correctness values

In [17]:
# set metadata to 1 if OK
assessed_content.loc[
    (assessed_content['text_DE'] == "// tag::DE[]") &
    (assessed_content['text_EN'] == "// tag::EN[]"), 'correctness'] = 1
assessed_content.loc[
    (assessed_content['text_DE'] == "// end::DE[]") &
    (assessed_content['text_EN'] == "// end::EN[]"), 'correctness'] = 1

### Create assessment output

In [18]:
assessed_content.to_html("translation_assessment_report.html", escape=False)
assessed_content.to_excel("translation_assessment_report.xlsx", index=None)
assessed_content.head()

,filename,link,text_DE,corrected_text_de,text_EN,corrected_text_en,correctness,assessment,line_DE,line_EN
0,../docs\00-preamble\01-what-to-expect.adoc,"<a href=""vscode://file/c:\dev\repos\curriculum...",// tag::DE[],,// tag::EN[],,1.0,"The provided texts are empty, making it imposs...",1,36
1,../docs\00-preamble\01-what-to-expect.adoc,"<a href=""vscode://file/c:\dev\repos\curriculum...",=== Was dieser Lehrplan enthält,=== Was dieser Lehrplan enthält,=== What Does this Curriculum Contain,=== What this Curriculum Contains,0.9,"The translation is mostly accurate, but the En...",2,37
2,../docs\00-preamble\01-what-to-expect.adoc,"<a href=""vscode://file/c:\dev\repos\curriculum...",Dieser Lehrplan für den _Certified Professiona...,Dieser Lehrplan für den _Certified Professiona...,This curriculum for the Certified Professional...,This curriculum for the _Certified Professiona...,0.9,"The translation is mostly accurate, but there ...",3,38
3,../docs\00-preamble\01-what-to-expect.adoc,"<a href=""vscode://file/c:\dev\repos\curriculum...",Seine Struktur orientiert sich an den grundleg...,Seine Struktur orientiert sich an den grundleg...,It is structured along the fundamental activit...,Its structure is oriented towards the fundamen...,0.9,"The translation is mostly accurate, but the ph...",5,40
4,../docs\00-preamble\01-what-to-expect.adoc,"<a href=""vscode://file/c:\dev\repos\curriculum...",* Anforderungen und Randbedingungen klären,* Anforderungen und Randbedingungen klären,* Clarifying stakeholder requirements and cons...,* Clarifying requirements and constraints,0.7,The translation captures the general meaning b...,7,42

### Set the threshold
Set the threshold for correctness. The default with 0.8 may be too ambitious.m

In [19]:
THRESHOLD = 0.8
needed_corrections = assessed_content[assessed_content['correctness'] < THRESHOLD]
display(HTML(needed_corrections.to_html(escape=False)))

### Produce output files

#### Create mergeable version

Produces a merge file to work with a merge editor. If you're brave, you can also set `is_override` to true to merge the suggestions of the LLM directly into the original file.

Tip: Overriding only should be enabled if both sections of the translations are almost structurally identically because otherwise it leads to complete chaos!

**Warning: Before setting it to True, make sure that you committed your local changes! Good luck!**

In [13]:
# flag for setting the override of the original file
is_override = False

# Group correctiony for each file to process each file only once
for filename, group in needed_corrections.groupby('filename'):
    # Open the file once for reading
    with open(filename, 'r') as file:
        lines = file.readlines()

    # Modify the relevant lines in memory
    modified = False
    for index, row in group.iterrows():
        if row['corrected_text_en']:  # Check if corrected_text_en is not empty
            line_number = int(row['line_EN']) - 1  # Convert to zero-based index
            # Insert merge-style corrections
            lines[line_number] = (
                f"<<<<<<< ORIGINAL\n{lines[line_number]}"
                f"=======\n{row['corrected_text_en']}\n"
                f">>>>>>> CORRECTED | German text: \'{row['text_DE']}\' (Line {int(row['line_DE'])}) | Assessment: {row['assessment']}\n"
            )
            modified = True  # Mark as modified since we are replacing the line

    # Write the updated content to a new file ending with '_merge.adoc'
    if modified:
        new_filename = filename if is_override else filename.replace('.adoc', '_merge.adoc')
        with open(new_filename, 'w') as file:
            file.writelines(lines)

        print(f"Merge-style corrected file saved as {new_filename}")

Merge-style corrected file saved as ../docs\00-preamble\01-what-to-expect.adoc
Merge-style corrected file saved as ../docs\00-preamble\02-out-of-scope.adoc
Merge-style corrected file saved as ../docs\00-preamble\03-prerequisites.adoc
Merge-style corrected file saved as ../docs\00-preamble\04-structure-timing-didactics.adoc

#### Create diffable version
Version that produces a separate file to work with a diff editor. It's disabled by default via the `is_active` flag because the mergable version is way better (IMHO).

In [14]:
# this is just a flag to set this block active or not
is_active = False

# Group by 'filename' to process each file only once
for filename, group in needed_corrections.groupby('filename'):
    # Open the file once for reading
    with open(filename, 'r') as file:
        lines = file.readlines()

    # Modify the relevant lines in memory
    modified = False
    for index, row in group.iterrows():
        line_number = int(row['line_EN']) - 1  # Convert to zero-based index
        lines[line_number] = row['corrected_text_en'] + '\n'
        modified = True  # Mark as modified since we are replacing the line

    # Write the updated content to a new file ending with '_corrected.adoc'
    if modified and is_active:
        new_filename = filename.replace('.adoc', '_aicorrected.adoc')
        with open(new_filename, 'w') as file:
            file.writelines(lines)

## Summary

Happy correcting!

Markus Harrer, October 2024